### PR TITLE
Add command line interface to upload videos

### PR DESCRIPTION
**Pull request by Yetangitu**
Add command line interface to upload videos. Use php -f upload.php -- -h in `view/mini-upload-form` for instructions. 

The -g parameter takes a comma-separated list of *NUMERICAL* groups (group IDs, actually) as argument, this due to the current absence of an easy way to get groups by their name, this can be changed when such has been implemented. I have not done this yet as there are things of higher concern, eg. the *abundance of SQL injection opportunities* in the code...).

```
Use: php -f upload.php -u <user> -f <file> [-d <description>] [-g "group1[,group2]] [-c] [-h]

    -u user     valid username
    -f file     input filename
    -d descr    description
    -g group(s) comma-separated numerical groups for which this item will be visible,
                item will be public if this is left out
    -c          copy original to destination directory (file will be moved if this is left out)
    -h          this help message
```

The easiest way to use this is to call the php code from a script, like so:

```sh
#!/bin/bash
srcdir="/var/src/YouPHPTube"

pushd "${srcdir}/view/mini-upload-form/" > /dev/null
sudo -u www-data php -f upload.php -- "$@"
popd > /dev/null
```

(adjust `srcdir` and `www-data` to your environment)

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
I have tested the command line help and didn't show me the help
image

**Comment by DanielnetoDotCom** [comment]
what the -f after php means?
php **-f** upload.php
i have remove it and works as expected
image

**Comment by Yetangitu** [comment]
The '-f' parameter tells *php* to parse and execute a file:

```
$ php -h
Usage: php [options] [-f] <file> [--] [args...]
 ...
  -f <file>        Parse and execute <file>.
 ...
```

Add a double dash after `upload.php` to tell php it should stop parsing parameters. The remaining parameters will be parsed by `upload.php`, like so:

```
$ sudo -u www-data php -f upload.php -- -h

Use: php -f upload.php -u <user> -f <file> [-d <description>] [-g "group1[,group2]] [-c] [-h]

    -u user     valid username
    -f file     input filename
    -d descr    description
    -g group(s) comma-separated numerical groups for which this item will be visible,
                item will be public if this is left out
    -c          copy original to destination directory (file will be moved if this is left out)
    -h          this help message

```

**Comment by DanielnetoDotCom** [comment]
With double dash works perfect.
But I think -f after php command is useless (at least for ubuntu)
What OS are u using?

**Comment by Yetangitu** [comment]
Try again with the double dash to see if it works for you with `-f`, it should. I'm using Debian, not that far from Ubuntu.

**Comment by DanielnetoDotCom** [comment]
Double dash works fine but the -f parameter is unnecessary on ubuntu

Em 5 de jun de 2017 15:37, "Frank de Lange" <notifications@github.com>
escreveu:

Try again with the double dash to see if it works for you with -f, it
should. I'm using Debian, not that far from Ubuntu.

—
You are receiving this because you modified the open/close state.

Reply to this email directly, view it on GitHub
<https://github.com/DanielnetoDotCom/YouPHPTube/pull/29#issuecomment-306268519>,
or mute the thread

**Comment by Yetangitu** [comment]
From `man 1 php`:

```
If none of -r -f -B -R -F -E or -S is present but a single parameter is given then this parameter is taken as the  filename  to  parse  and  execute
(same as with -f). If no parameter is present then the standard input is read and executed.
```

In other words, leaving out `-f` works if there are no other parameters for php but there is a single unnamed parameter.

**Pull request merged**
