### PR TITLE
updated options/designs

### PR DESCRIPTION
**Pull request by hersche**
like descripted in the last PR;
- litedesign reworked
- litegallery implemented
- add cat to youphpflix (besider views and likes, when hover a video)
- optionalise of most- watched popular and newest-cat's. enabled by default, disable when wanted.
- optimised sql-traffic in compare to last litedesign

looks like it is more or less "bug-free", at least i didn't reconize bad effects..

i will do the unstable-branch when i've further ideas, so should stay stable :)

### CODE REVIEW

**Comment by hersche** [comment]
please wait a sec for now with merge, i've found ugly html in gallery-plugin, may from resolve the merges

**Comment by hersche** [comment]
is fixed (hope i didn't remove your wanted changes?)
Also there are more options, which improve flexibility when needed (rowCount).

**Comment by hersche** [comment]
a bit a offtopic question, but what's your way to update existing tables properly? in my unstable-branch i had implement a option i like (disable rightclick on video), but only respected install.sql since now.

**Comment by DanielnetoDotCom** [comment]
To update existing tables you need to create an update file, check the update dir

In example, you will need to create a new YPT version you will need to create the file updateDb.v4.8.sql

Also update the install dir files:
change checkConfiguration.php  `$installationVersion` variable change it to `$installationVersion = "4.9";`

and I think you will be all set

**Comment by DanielnetoDotCom** [comment]
BTW, the gallery I just tested and it is great

**Comment by hersche** [comment]
thanks for your explaining and compliment :)

**Pull request merged**
