### PR TITLE
This commit sets thumbnails to letterboxed if they are portrait or sme other aspect that is not 16:9

### PR DESCRIPTION
**Pull request by OhioVR**
Hello,

It looks like there is a lot of edits to this file but it being caused by my autoformatter. If you reject it because of that I suppose that is fine. I can't figure out how to make the formatter jive with the style you have. Anyway this is a simple change, what it does is render the thumbnail as a letter box if the aspect ratio is something other than 16:9. This pull request compliments my other one for the encoder published today.

### CODE REVIEW

**Comment by OhioVR** [comment]
BTW I made a video of what this is for:

https://www.youtube.com/watch?v=hA_LMRyBUZQ

**Comment by DanielnetoDotCom** [comment]
Thanks for your change

I will accept but I will need to add an option to use im_resizeV3, and the default will be im_resizeV2

because many of streamers does not have ffmpeg on their servers. FFMPEG is required only for encoder.

about the stretched video you may change your ffmpeg code to -2 on the width

this will retain the spect radio 
image

**Comment by OhioVR** [comment]
That is interesting, looks fairly robust enough. The trouble is the SD and HD default setting weren't done with the -2 option by default and I always tested my videos at a higher resolution. Could it be set by default?

**Comment by DanielnetoDotCom** [comment]
on olds installations, it was not the default, but all new installations the -2 will be the default.

**Comment by OhioVR** [comment]
I've been installing with a custom Docker file from your git repo. I think these are the latest values:

https://github.com/DanielnetoDotCom/YouPHPTube-Encoder/blob/master/install/database.sql

(7,'MP4 SD','ffmpeg -i {$pathFileName} -vf scale=720:540 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}',now(),now(),'mp4','mp4',11),

(8,'MP4 HD','ffmpeg -i {$pathFileName} -vf scale=1280:720 -movflags faststart -preset ultrafast -vcodec h264 -acodec aac -strict -2 -y {$destinationFile}',now(),now(),'mp4','mp4',12),

That's what shows up in my encoder settings area at least.

A fresh install has problems with non 16:9 aspect ratios. I'm not sure what I'm missing here.

**Comment by DanielnetoDotCom** [comment]
OMG, you were right.

I just sent an update for it

**Pull request merged**
