### PR TITLE
Update to 5.1

### PR DESCRIPTION
**Pull request by hersche**
i try to collect what i've done / changelog:
* implementing subcategories
   * integrated in youphpflix- and gallery-plugin and navbar (view)
* implementing audio
   * in mp4-upload
   * in plugins (hotkeys, theater-button, seek-button,next-button)
   * in youphpflix (you can activate a seperate audio-gallery)
   * allow jpg-cover in youphpflix and on player-site
* implement category-type
   * autodetect or manual (in admin-category-site)
   * allows optimations (example-idea: audio-playlist and separated (audio/video) category-list)
* add download-button to gallery- and youphpflix directly, when activated
* style-fix for description-button in gallery-plugin
* various small fixes since last time..
   * JS-exceptions (maybe from myself)
   * after being logged out by timeout -> error message -> login ->false, repeated error-message again :fixed (at least en and de, other languages need a translation)

* not fully finished: preview from subcategory in category-gallery in youphpflix (only, when no video is avaible in parent-category)

this PR needs:
a) a bit more testing
b) @DanielnetoDotCom 's changelog
c) finishing the unfinished point..

it feels stable, but is still very fresh..
my bigger installation is offline now and not avaible (there i would like to test it as well), but local i find nothing unfinished. anyway, would feel better, when some other people than me try it too..

### CODE REVIEW

**Comment by gamersalpha** [comment]
so cool how use this version ?

**Comment by DanielnetoDotCom** [comment]
That is amazing, thanks, I am finishing something this week, and my next step will be merge this pull request.
We will release it this week for sure

**Comment by hersche** [comment]
... and we should still test a bit.. 
until yesterday, i still found stuff/bugs, it's corrected now, but maybe there's also other stuff.. better release a day later, but more stable :)

**Comment by DanielnetoDotCom** [comment]
The problem is the things I am working with I need to change Gallery plugin now.
I think will be a conflict

**Comment by hersche** [comment]
ok, i see, you've merged.. cool :)

conflicts generally can be resolved (i do this sometimes in youphptube), but i hope now, nothing will break out there.. but i think you've tried it out quick, before merging..?

**Comment by hersche** [comment]
yeah, no problem.. but i'm a bit confused..

https://github.com/DanielnetoDotCom/YouPHPTube/pull/563/files

https://github.com/DanielnetoDotCom/YouPHPTube/commit/7f7d1c6201be5b91f8a9d3046087e92977e76b37

didn't you catch all the code from me, by merging? looks like you had to paste some stuff after merge..

btw, as i said, i / we should test it a bit first.. for next time, that would be cool. i also will do update-merges to my repo, so we wouldn't have conflicts..

**Comment by DanielnetoDotCom** [comment]
I did catch all the code, but it for some reason messed up my IDE.

but is fixed now.

I am separating Gallery in files to make easier control

**Comment by hersche** [comment]
ok, what IDE you use? (would be interessting anyway)
brackets don't have a good formatter, but this should be limited to php-files in my case (still confused about the .sql's). but anyway, nice to have more structure in the gallery-part.. :+1:

**Comment by hersche** [comment]
subcategorys and back-button are not shown anymore in gallery-plugin.. i think you're still in refactoring the stuff to methods and are active developing this minutes?

if not i will have a look to it, but this is kind of essential to my installation..

**Comment by hersche** [comment]
found the bug:

in modeGallerie.php


          if (!empty($video)) {
                if (!empty($currentCat)) {
                        include $global['systemRootPath'] . 'plugin/Gallery/view/Category.php';
                    }

should be


                if (!empty($currentCat)) {
                        include $global['systemRootPath'] . 'plugin/Gallery/view/Category.php';
                    }
          if (!empty($video)) {

cause there can be sub-categorys, also when no video is in this category..

**Comment by DanielnetoDotCom** [comment]
I am away from PC now. I have sent the comit from my last modifications . So fell free to fix any bug founded 

Soon I will need to use gallery in one project here , that is why I have accept the pull request

**Comment by hersche** [comment]
ok.. you will have a very small PR in some sec's

**Comment by gamersalpha** [comment]
Hello there, 

where is this version, where i can install it and try it ??

thanks

**Comment by hersche** [comment]
hey, it's already merged, so you can get the official sources (https://github.com/DanielnetoDotCom/YouPHPTube) and you have it (git clone or zip-download)

my dev-branch is here: https://github.com/hersche/YouPHPTube/tree/unstable

**Pull request merged**
