### PR TITLE
Update to managerUsers.php for user options

### PR DESCRIPTION
**Pull request by Criptos**
Updateing the change

### CODE REVIEW

**Comment by hersche** [comment]
can you please provide a example of how the userexamples will look first?

**Comment by Criptos** [comment]
At plugin: 
`    public function getUserOptions()
    {
        $userOptions["Has Options Test"]="hasOptionsTest"; 
        $userOptions["Yes it does!"]="yesItDoes"; 
        return $userOptions;
    }`

Index is the text of the switc button and the value is the id to store as externalObject and used as the javascript id 
 
`MariaDB [pa_desarrollo]> select * from users where id=3\G; 
*************************** 1. row ***************************
             id: 3
           user: PoleAccess
           name: PoleAccess
          email: support@poleaccess.online
       password: ac7a9b6178d9d1d094d89435b28bc6f3
        created: 2018-06-06 22:01:34
       modified: 2018-07-02 02:21:07
        isAdmin: 0
         status: a
       photoURL: videos/userPhoto/photo3.png
      lastLogin: 2018-07-02 02:21:07
    recoverPass: 5b18a45447647
  backgroundURL: videos/userPhoto/background3.png
      canStream: 0
      canUpload: 1
   canViewChart: 0
          about: 
    channelName: PoleAccess
  emailVerified: 1
  analyticsCode: 
externalOptions: YTozOntzOjEyOiJhY2Nlc3NFdmVudHMiO3M6NDoidHJ1ZSI7czoxNDoiaGFzT3B0aW9uc1Rlc3QiO3M6NToiZmFsc2UiO3M6OToieWVzSXREb2VzIjtzOjU6ImZhbHNlIjt9
`

externalOptions is sabed as a serialized object base_64 for protection: 
YTozOntzOjEyOiJhY2Nlc3NFdmVudHMiO3M6NDoidHJ1ZSI7czoxNDoiaGFzT3B0aW9uc1Rlc3QiO3M6NToiZmFsc2UiO3M6OToieWVzSXREb2VzIjtzOjU6ImZhbHNlIjt9
 
translates to: 
a:3:{s:12:"accessEvents";s:4:"true";s:14:"hasOptionsTest";s:5:"false";s:9:"yesItDoes";s:5:"false";} 

To unserialize: 
$a=unserialize(a:3{s:12:"accessEvents";s:4:"true";s:14:"hasOptionsTest";s:5:"false";s:9:"yesItDoes";s:5:"false";});

From 2 plugins, the optionsTest provides hasOptionsTest and yesItDoes and EventsTicket provides accessEvents.

**Comment by hersche** [comment]
thank you!

this looks quite compact. also i retried it quick and can confirm it works. nice done then!

**Comment by Criptos** [comment]
Thanks! :)  
 
I think it was a nice update for the framework and interlocked :)

**Pull request merged**
