### PR TITLE
Bypassing unecessary Enconding, Allow MySQL other than the default 3306 port connection, CSS Flexbox in the header and new style in the Footer

### PR DESCRIPTION
**Pull request by tiagostutz**
I adjusted the header elements position and style to use CSS Flexbox, as it is more 'stable' than inline-block and float strategy. Also, I have changed the footer color to be more smooth with the overall layout color.

captura de tela 2017-07-20 as 21 12 27

### CODE REVIEW

**Comment by tiagostutz** [comment]
fixes #66

**Comment by tiagostutz** [comment]
fixes #70

**Comment by DanielnetoDotCom** [comment]
Looks Like great merge

**Comment by tiagostutz** [comment]
This closes #70 and closes #66

**Pull request merged**
