### PR TITLE
Adds 4 new capabilities to plugins.

### PR DESCRIPTION
**Pull request by Criptos**
Adds 4  capabilities to plugins: 
1) add custom routes
2) add custom configuration variables to CustomizeAdvanced and removes it when disabled
3) add user options to admin interface
4) add menu button to menu bar from the plugin

Example object included.

### CODE REVIEW

**Comment by Criptos** [comment]
test object added

Custom options added: 
image

User options added:
image

**Comment by Criptos** [comment]
Buttons added to the nav bar from the plugins... 

image

**Comment by DanielnetoDotCom** [comment]
@Criptos the Option Test plugin is not clear to me, also I could not found the add buttons on navbar plugin

**Comment by DanielnetoDotCom** [comment]
And what is externalOptions used for?

**Comment by hersche** [comment]
i am also not shure about that.

what kind of info you save there? 

then, the db-change has also to be done on install.sql

also, the php-router is inactive by default atm. so change-routes will not work for most installations out there.

if it is active, a special variable will be set, you can check it by this variable if you can use it or not.

by the way, do you plan to publish the plugins you made with this extensions also public?

**Comment by hersche** [comment]
and can i clean up the root-dir of the project?

there is objects, plugins and view as a folder, do we need really copies of files from there in the root? do i miss any sense on that?

**Comment by Criptos** [comment]
Hello everyone...

The plugin will have 2 parts, one 'free' that allows you to create and
provide tickets.
And the second, non free, to allow to actually sell the tickets.


Vinzenz, I don't know, maybe I just... cpied by mistake? what files?
directory?



Oooh... I forgot about the install.sql...

My mistake.. is my first 'big' plugin with changes.


I work this way. I have my own developtment environment and an upstream
directory, which is the one I modify and then merge and sync with master...

THe optionTest pluin is just for test the options.. of what they do and how
to work with them...

**Comment by hersche** [comment]
> Vinzenz, I don't know, maybe I just... cpied by mistake? what files?
> directory?

root-directory..

- https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/userAddNew.json.php
- https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/user.php
- https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/YouPHPTubePlugin.php
- https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/Plugin.abstract.php

>  The plugin will have 2 parts, one 'free' that allows you to create and provide tickets.

externalOptions (users table in db) is to save those tickets from the plugin, do i understand this right?

**Comment by Criptos** [comment]
Ok, the idea is to provide sitem wide configuration options to plugins, adding them to  CustomizeAdvanced plugin. 
User configuration options added to de managerUsers.php 
and finally you can add navBar menus. 

In the case of objectTests the navBar buttons are validated if the user has the option setup. 
The new filed added, is an base64_encode of the serialzed array of user options, so they can be saved in bulk and consulted using user::externalOptions($id) or user::getexternalOptions($id) so you can test per user configuration. 

Abour routes, I know they are'nt fully deployed in old instalations, but simple::router is simply a much more solution...
 
The object testOption,  provide all of this, and also, the navbar buttos are controller by user options... 


 
image

**Comment by Criptos** [comment]
@hersche  externalOptions saves  userOptions... 

 The tickets will have their own couple of tables, one for events, and the other for tickets. 

The final goal is to be able to have 'differnt type of users' 
One type of 'free users' for example: can post and comment. 
Not so free users: can livestream 
Paying users: can create events. 
Very paying users: can charger per evets.  (obviously with a fee ) 

And about the files... sorry my copy mistake... 
Doing the cleanup rigth now.

**Comment by hersche** [comment]
ok, can you provide a example how such userOptions would look?

sounds interessting :)

**Comment by Criptos** [comment]
I saw what happened, I botched the copy of my files and ended up at root... 
did some cleaning up...

**Comment by hersche** [comment]
saw and merged it.. option-example would still be very interessting to me.

also, for compatibility, i added this line once: https://github.com/DanielnetoDotCom/YouPHPTube/blob/master/index.php#L3

by checking if $phprouter, you can decide, if you use rewritten url's or if you use direct links (looks ugly, but work). i also have a idea in mind to make translated addresses, thats a pro of the php-router, but if the classic.htaccess is active (the default), then the phprouter never get touched - and this is maybe more performant (very little i think). 

so, provide both, php-router or individual webserver-rewrites (=no php-router in future), would be the best, absolutly needed in core in my opinion, nice in plugins and easy to do anyway ;)

**Comment by DanielnetoDotCom** [comment]
@Criptos If you wold like you can create a video how it works. I can publish it on https://tutorials.youphptube.com/ 

It still not clear to me.

**Comment by hersche** [comment]
it was continued here a bit: https://github.com/DanielnetoDotCom/YouPHPTube/pull/818

maybe it helps you understand the saved options.. 

i am quite unshure, if we can't do it more proper by a nameconventions. the point is a bit: if a plugin want to provide options in managerUsers.php, it will badly be able to save it on it's own, because it's all going to user's json for save it.

so, i think it's the most easiest to save it to the user, for the checkboxes you can do a simple

    $userOptions["Has Options Test"]="hasOptionsTest"; 

so far so good, but now, if we have too much plugins, all that stuff will be saved in the user's session, will be transmitted for most user-request and only allow checkboxes.

i imagine it more flexible like

    $userOptions[]="<label>Optionstest</label><input type='checkbox' id='pluginsconfig_optionstest_".$this->getName()."' >"; 

so we can get by pluginsconfig_ , that it is a such config and we can save it then to a separate table for the concrete plugin in user's json for update it.

the advantages are, that we can provide all kinds of input (dropdown for example), user would stay slim and the plugin can load the config specific when it's needed (instead of every site-call)

**Comment by DanielnetoDotCom** [comment]
Got it, great Idea @Criptos

**Pull request merged**
