### PR TITLE
version 4.9

### PR DESCRIPTION
**Pull request by hersche**
hello,

// first, this PR is not ready yet - it should be to discuss first!
first, this comment is very massive edited, since i assume no one read it yet. if someone read it, don't be confused ^^

at the moment i work on https://github.com/hersche/YouPHPTube/tree/unstable , which also include database-changes. this is out of these reasons:

- make youtube-upload disable-able (button and text) (option, default is off)
- make rightclick-restriction disable-able and add download-button under video (which use title for the download-filename) (option, default is off)
- add category-description (sql-text-field)

the first both options are, because i use it home-internal where we have a lot of movies, which would be restricted on youtube cause of copyrights. but at least in switzerland it's legal for private use. and when you go out of the (internal) network, it could be very usefull to have a dvd-backup in your phone for offline-use ;)

i've commited a change, so the admin can see a db-update avaible - this is default in a lot of cms's and i find it very usefull, because this db-stuff can do nasty bugs... 

text-message could be editet and should be translate-able too, but at least it's there, and this also only for the admin on admin-like sites (ressources).

i know i want to merge here my master-branch but do the stuff in the unstable-branch - to explain, i will merge unstable to my master when it's ready, after this, this PR should be done.

since it's a version-change you may have more ideas to implement? also a little review could be nice, i may also will do other changes, but not shure yet.

regards 

vinz

### CODE REVIEW

**Comment by hersche** [comment]
at the moment i've a bit weird bugs in unstable (master untestet):
- search prints only sql-command
- login is first time after login not reconized (reload solves it)

**Comment by DanielnetoDotCom** [comment]
All those ideas are great. all those are necessary features

The only thing I ask to pay attention is the version number.

I am about to release a new version, probably 4.9, and yours should be 5.0 or greater, depends when you release it

**Comment by hersche** [comment]
mh, i always think, it should be ready, but as before some minutes, i still build other features i have to test.

the latest is again kind of sorting: it's a option in the category, which change the autoplay-order (when next_video is not set). at the moment my new mode is set to title-name, but the old random-choose is the default

this way, a lot of work can be saved; if the name is right, there's no need for set next_video anymore.

also i find it usefull to bind it to a category - when you have a serie, you could set it this way, if you have indipended movies in another category, you can let the old way be.

since it's a nr, i think about build in also other modes, like choose by date.

also i had a nice effect, which i let stay - when the category ends, after it's gone through by title, also autoplay ends, since i not set $autoplayvideo again..

that's some heavy changes, are they ok for you?

can you test it anywhere? but, it's also fresh, may you encounter bugs. also view is not 100% finished!

**Comment by hersche** [comment]
i've merged unstable to master, because i'm feel ready.

i only increased to 4.10 instead of 5.0. is this ok for you or would you like to call it 5.0?

btw, another test would not be bad, but i know nothing that really don't work anymore..

**Comment by hersche** [comment]
i've tested it with a fresh installation (also because of plugin-settings) and saw no problems so far. looks a bit, like it ever looked, cause most things i made you have to activate first / are optional..

**Comment by hersche** [comment]
i've began to integrate audio directly into streamer / "mp4-upload".

it's not fully finished, but works basicly. should i merge this from unstable to master as well (so you can continue as you like) or should i test it first? since it's still in unstable only, you can merge this withouth problems (also when i found nothing crashing by sound)

**Pull request merged**
