### PR TITLE
Hide sensitive info

### PR DESCRIPTION
**Pull request by ChrisSlS**
https://github.com/DanielnetoDotCom/YouPHPTube/commit/3cee2542fdcd8796f967de88ba1f88fe52cbf8d4#diff-6bf6022a99ea90672b499f9158e726a9R221

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
Hi @ChrisSlS 

I agree I need to find another way to connect the Encoder.
But if you remove it we will not have the automatic login anymore

**Comment by ChrisSlS** [comment]
I'm not sure I understood your message. The modified file is managerVideos. It displayed login information in the url, but now it works like navbar. I just used the encoder without problems, automatically login and the video has been sent to the site

**Comment by DanielnetoDotCom** [comment]
here is the navbar form

https://github.com/DanielnetoDotCom/YouPHPTube/blob/3dfe7bdeccef8b556b0c027914f66f11e2da5a03/view/include/navbar.php#L223

and you are suggesting to change the view/managerVideos.php file

**Comment by ChrisSlS** [comment]
I tried adding this line (and the ones below), but it did not work.

Sorry for my ignorance, I start in PHP and I'm far from understanding everything

**Comment by ChrisSlS** [comment]
I see, thank you.

Do you think it's a good idea to leave it on my site ?

**Comment by DanielnetoDotCom** [comment]
Yes, that last post works :)
hanks

**Pull request merged**
