### PR TITLE
youphpflixhybrid-plugin and small refactorings in hotkeys-plugin

### PR DESCRIPTION
**Pull request by hersche**
youphpflixhybrid is a plugin that uses youphpflix ONLY for the startpage. when you search or go to a category, the gallery-plugin is used instead.

For me, this makes absolut sense for a better overview.

The plugin is made very simple and use the existing files, so there's no need to update redundant files.

the bit bad of this PR: commit "Prepare for store and get subtitles". This can be reverted or continued, i would remove it but i think that's not possible (except reset the repo completly).

best regards

vinz

edit: add a fix for hotkeys-plugin and gallery-plugin.

edit 2: i have a better condition for my modeGallery-patch, but my place to test is offline until tomorrow - expect it soon ;) also you can see, i've done some other little stuff as well..

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
Hey @hersche 

Great work, thanks for your contribution :)

There are 2 thing I would like to let you know 

1 - We had some problems on the license. the part (must be user for good never for evil) x (AGPL). so I changed the license for JSON. if you do not have problems with it your update is very welcome.

2 - Another thing is the part I realized with **subtitles** support. I saw a class and I also saw the tables in the database, however I did not see the update file for a new version and I also did not see a view or plugin to use. and this will generate a conflict with the existing subtitles plugin.
would it be possible to remove this part of the subtitles from your pull request? if you want I can accept and remove it as well.

But in a general way is very good, we can see that you have a lot of talent with PHP

**Comment by DanielnetoDotCom** [comment]
Sorry I just see you said you cant remove the subtitle, I can do that if you accept the new license and do not mind :)

**Comment by hersche** [comment]
well, i'm personally not christian and good or evil is always relative, but i hope, the software will not be used for pedo-stuff, ad's or real violence.. 

also, the json-license looks really open.. so far, all good. i acceppt.

removing the subtitle-stuff is something you can do, maybe i would finish it one day (i dont want to make fake-promises) when you let it stay..

also, the better/more exact condition is tested and pushed now :)

> and this will generate a conflict with the existing subtitles plugin.

there's a existing one? have to check :))

**Comment by DanielnetoDotCom** [comment]
@hersche I just merge your pull request, can you please check on demo site?
I cant see much difference from the original youphpflix

**Comment by DanielnetoDotCom** [comment]
Never mind, I just understand, when you select a category you have gallery style
Great work thanks

**Pull request merged**
