### PR TITLE
Added 2 new functions for plugins

### PR DESCRIPTION
**Pull request by Criptos**
No allow to place buttons at the playlist interface, it will be used for the loop and fullscreen playlist options. 

I ned to rework the loop code based on the new  changes, but I don't want to keep fiddling with this two functions each time YouPHPTube is updated...

### CODE REVIEW

**Comment by hersche** [comment]
that's fine for me, but i dislike those lines:

https://github.com/DanielnetoDotCom/YouPHPTube/pull/800/files#diff-4179ffaf02df3204f8f6dc5a87086e6bL46

i need the getChartContent-method, else at least one plugin is breaking. also it make sense for further projects. i assume it's a mistake, but i please you to implement this again.

**Comment by DanielnetoDotCom** [comment]
@Criptos just put the getChartContent back and we are fine to approve it

**Comment by hersche** [comment]
@Criptos just a small thing: right now, you only are done with the structure by the 2 files. but like this only, it will not be executed anywhere.
wouldn't make it sense to integrate it to view/include/playlist.php and execute your getPlayListButtons($playlist_id="")-method there, so it will extend the playlist-buttons for real?

**Comment by Criptos** [comment]
The effect I'm looking for tis this: 
image
 
 
So I can decide which playlist would be looping and which one not...

**Comment by hersche** [comment]
ok, but i think the buttons you like to place are for now on the left site. you can float that in the plugin, but maybe move the execution after the rename-button instead of play all is easier.

**Comment by Criptos** [comment]
They are at the most rigth place...  I didn't understand you... they are placed at the far rigth, because I didn't want the to be confused with the play all..

**Comment by hersche** [comment]
what i mean is, behind / under this line

https://github.com/Criptos/YouPHPTube/blob/594973091c5b8f22e6fd25b646356c69d1f356a3/view/channel.php#L174

because in your screenshots the new buttons are behind the delete and rename-button.

but in your source, it is after this line
https://github.com/Criptos/YouPHPTube/blob/594973091c5b8f22e6fd25b646356c69d1f356a3/view/channel.php#L145

contain 

echo __("Play All");

this is on the left site.
playlist - screenshot_20180627_051606

after where i have placed the mouse-pointer.

but anyway, for me it doesn't matter.

**Pull request merged**
