### PR TITLE
updates

### PR DESCRIPTION
**Pull request by hersche**
- some stabilize-stuff on my own plugins
- changes in gallery-plugin, don't know if all are wanted for all
   - description as a popover
- small changes in youphpflix (handling of overflow)
- mvideos shows if next video is set or not (in overview)
- the .updateSrc -> .src was build in and is now double PR - my motivation was the stay-in-fullscreen-feature

as always, you have to know what you wanna revert and what accept..

best regards

vinz

### CODE REVIEW

**Comment by DanielnetoDotCom** [comment]
I had to remove LiteDesign, there are some tags missing or in wrong place, breaking the layout

image

**Comment by DanielnetoDotCom** [comment]
Another issue


image

**Comment by DanielnetoDotCom** [comment]
I had to remove LiteDesign, there are some tags missing or in wrong place, breaking the layout

**Comment by hersche** [comment]
well, yes, litedesign is a really new idea i had, cause showing all videos in one page use too much cpu on older devices.. i'm still not finished there. Also i did some more, bit unstable mods on gallery-plugin.  I'm sorry, some stuff was not thinked/ready for this PR.

**Comment by DanielnetoDotCom** [comment]
No problem, but next time, make the pull request after make sure it is working :)
Also try not to use inline css, first try to use bootstrap class.

**Comment by hersche** [comment]
ehm, this is a missunderstanding. i made first the pull-request, then continue coding. all the new commits are added automaticly. so i would have to open another branch for this, but that means more need of overview (which i already need, since i wanted to continue with ajaxing / stay-in-fullscreen)

mh, you did reset the gallery-plugin at all? bigpicture-option is also uninteressting? sort by name is generally for nothing or was it because of the style-break? that text is not endless long (did you test with lorem ipsum?)?

please tell me what you think about this changes - i mean, of course it should work, but i mean the ideas..

bootstrap is nice, but either i don't have enough "expirience" with it or have to replace values (!important).
there i'm a bit "retro"..

btw, did you get the second mail?

**Comment by hersche** [comment]
i am really sorry, i was on the wrong branch (stay-in-fs), which simply was not updated. you let the options in the plugin-class stay, thanks. i also did a rewrite of the litedesign now, which is much more proper, since it only have one if-else.

to understand those effects, i've to tell you maybe, that my electric complete on solar. so, while hacking through the night, it can be, that i'm only on battery and therefore a bit stressed (and tired). also i commit for updating my server (a local rpi). for the next time, i will make myself a unstable branch and merge back to master, when i think it's stable..

**Comment by DanielnetoDotCom** [comment]
Hi, yes I got I agree and I will answer you soon.

I hope you to send another pull request soon.

**Pull request merged**
